### ISSUE TITLE
Doesn't work with symbolic links

### ISSUE THREAD

**Issue by ovikholt** [ovikholt/dulsort#1]
Output tail:

```
   ...
   21G Dropbox
   30G Movies
..... awesome-porn-samba.mp3
..... ChmodBPF.tar.gz
..... fra-jobb-pc-dotfiles.tar
('total time spent:', 37.75939702987671)
Traceback (most recent call last):
  File "/Users/ovikholt/bin/dulsort", line 161, in <module>
    main.run()
  File "/Users/ovikholt/bin/dulsort", line 88, in run
    stat_tuple = os.stat(filename)
OSError: [Errno 2] No such file or directory: 'SP PHD U3'
```

**Comment by ovikholt** [comment]
Fixed by d0143da
